### ISSUE TITLE
User Story: As a user I want to have a “My Favorites” section so that I can save and quickly access products I am interested in purchasing later

### ISSUE THREAD

**Issue by didi1211** [KYH-Net23/WishlistProvider#1]
# Acceptance Criterias 

- [x] The user should be able to add products to the "My Favorites" section from any product details page.
- [ ] If a product is not able to be added (server, internet issues) then there will be an on screen message saying that item/product couldnt be added to “my favorites” and the user is prompted to retry.
- [x] if a product is successfully added to my favorites there should be an on screen message saying that “product/item is added to My Favorites”. 
- [x] The "My Favorites" section should display a list of saved products, including product name, price.
- [x] The user should be able to remove products from "My Favorites"
- [x] The user should be able to click on any product in "My Favorites" to view the product details page.
- [x] If there are no items in "My Favorites" a message should be displayed indicating that the section is empty.

---

# Tasks

- [x] Implement an Add to Favorites Functionality on product details page
- [x] Design "My Favorites" page layout that displays saved products with relevant information (price, name)
- [ ] Develop Backend Logic to Save Favorites
- [ ] Store the user’s favorite products in the database, ensuring changes are saved
- [x] Display a list of saved products in "My Favorites" (price, name)
- [x] Allow users to click on any product in "My Favorites" to navigate directly to the product details page.
- [x] Add a "Remove" button for each item in "My Favorites" that allows users to delete products from their list
- [x] Display a message for an empty "My Favorites" list ( ex. you have no favorites yet")
- [ ] Implement error handling to manage cases where adding or removing items fails(on screen message relevant to error)
- [x] Include a back button to help users return to the previous page from "My Favorites."

---

# Activity Diagram 

![Image](https://github.com/user-attachments/assets/46ee9e2a-658a-4001-bb32-6e996f95791c)

--- 

# Sequence Diagram 

![Image](https://github.com/user-attachments/assets/3b7ab2c5-0871-4f2c-ab03-4b6c911ece39)

---

Test Case Descriptions

- [x] Test Case 1: Adding a Product to "My Favorites"

Prerequisites: The user is logged in and viewing a product page.

Steps:
Click on the "Add to Favorites" button on the product page.
Navigate to the "My Favorites" section.

Expected Result: The selected product is added to "My Favorites" and appears in the list with product details(name, price)

---

- [x] Test Case 2: Removing a Product from "My Favorites"

Prerequisites: The user has at least one product in "My Favorites."

Steps:
Navigate to the "My Favorites" section.
Click on the "Remove" button next to a saved product.
Verify that the product is removed from the list.

Expected Result: The selected product is removed from "My Favorites," and the change is saved.

---

- [x] Test Case 3: Navigating to Product Details from "My Favorites"

Prerequisites: The user has at least one product in "My Favorites."

Steps:
In "My Favorites," click on a product to view its details.
Verify that the user is redirected to the correct product details page.

Expected Result: Clicking on a product in "My Favorites" opens the product details page for that item.

---

- [x] Test Case 4: Viewing "My Favorites" When Empty

Prerequisites: The user has no products in "My Favorites."

Steps:
Navigate to the "My Favorites" section.
Verify that a message is displayed indicating that there are no favorite items.

Expected Result: The "My Favorites" page displays a message such as “You have no favorite items yet.”

---

- [ ] Test Case 5: Handling Failure to remove product from “My Favorites”

Prerequisites: The user is on the "My Favorites." section with server or internet issues.

Steps:
Click on the remove button to remove a product from “my favorites”
Verify that a message is displayed indicating that product could not be removed and is prompted to try again later.

Expected Result: There will be an on screen message indicating that item could not be removed and is prompted to try again later. 

---

- [x] Test Case 6: Handling Failure to add to “My Favorites”

Prerequisites: User is in the “Product detail” section and has server or internet issues.

Steps:
Click on add to Favorites
Verify that a message is displayed indicating that product could not be added to “My favorites”

Expected Result: There will be an on screen message saying that item/product could not be added to “my favorites”
